name: Scheduled Workflow  

on:
  schedule: 
    - cron:  '0 0 * * *'  

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  
      - name: Update pip
        run: python -m pip install --upgrade pip  
      - name: Install requirments
        run: pip install -r requirements.txt 
      - name: Run sign
        run: |
          python Auto_SignIn.py