name: Star Repo Workflow

on:
  repository_dispatch:
  release:
    types: published

  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update pip
        run: python -m pip install --upgrade pip  
      - name: Install requirments
        run: pip install -r requirements.txt 
      - name: Run sign
        run: |
          python Auto_SignIn.py
